name: Docker

# Esto le dice a GitHub que construya la imagen cuando hagas cambios en V3/develop
on:
  push:
    branches: [ "V3/develop" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # Esto usará mathygamersYT/Red-DiscordBot
  IMAGE_NAME: mathygamersyt/red-discordbot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Esto creará la etiqueta :latest
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
